// Generate dist/sanskrit-util.global.js — a browser <script>-loadable IIFE build of index.mjs,
// for consumers that can't use ES modules (plain static pages: WhitneyRoots reader.js, v3_app.js).
// index.mjs stays the SINGLE SOURCE; this is a deterministic, zero-dependency textual transform:
// strip `export`, drop the default-export object, wrap in an IIFE that assigns globalThis.SanskritUtil.
//
// Run:  node build-global.mjs        (regenerate)
//       node build-global.mjs --check  (fail if the committed file is stale — used by CI)
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const src = readFileSync(join(here, 'index.mjs'), 'utf8');

// Names this module exports (both `export function f` and `export const C`).
const names = [...src.matchAll(/^export\s+(?:function|const)\s+([A-Za-z_$][\w$]*)/gm)].map((m) => m[1]);
if (!names.length) throw new Error('no exports found in index.mjs');

const body = src
  .replace(/^export default \{[\s\S]*?\};\s*$/m, '')   // drop the ESM default-export object
  .replace(/^export\s+(function|const)\s/gm, '$1 ')    // `export function`/`export const` -> plain
  .trimEnd();

const banner = `// GENERATED by js/build-global.mjs from js/index.mjs — DO NOT EDIT BY HAND.\n`
  + `// Browser global build: load via <script src="sanskrit-util.global.js"></script>, then use\n`
  + `// window.SanskritUtil.norm(...), .to_slp1(...), etc. Behaviour-identical to the ESM index.mjs.\n`;

const out = `${banner}(function (root) {\n  'use strict';\n\n${body}\n\n`
  + `  root.SanskritUtil = Object.freeze({\n    ${names.join(', ')},\n  });\n`
  + `})(typeof globalThis !== 'undefined' ? globalThis : this);\n`;

const target = join(here, 'sanskrit-util.global.js');

if (process.argv.includes('--check')) {
  let current = '';
  try { current = readFileSync(target, 'utf8'); } catch { /* missing */ }
  if (current !== out) {
    console.error('STALE: js/sanskrit-util.global.js is out of date — run `node js/build-global.mjs`.');
    process.exit(1);
  }
  console.log(`OK: global build current (${names.length} exports).`);
} else {
  writeFileSync(target, out);
  console.log(`wrote js/sanskrit-util.global.js (${names.length} exports: ${names.join(', ')})`);
}
