// GENERATED by js/build-global.mjs from js/index.mjs — DO NOT EDIT BY HAND.
// Browser global build: load via <script src="sanskrit-util.global.js"></script>, then use
// window.SanskritUtil.norm(...), .to_slp1(...), etc. Behaviour-identical to the ESM index.mjs.
(function (root) {
  'use strict';

// sanskrit_util — shared Sanskrit string helpers for the CDSL / Sanskrit-Lexicon repos.
//
// Behaviour-identical port of py/sanskrit_util/__init__.py (proved by ../vectors/vectors.json).
// Consolidated from WhitneyRoots reader.js (deva2iast/norm/nfold), linguistics.js
// (normalizeSanskrit/iastToDevanagari) and scripts/sanskrit_util.py (to_slp1/from_slp1/
// to_roman/form_key). See README for which key to use when.

// ---- IAST -> SLP1 (longest-key-first; aspirates + diphthongs are digraphs) ----
const SLP1 = {
  ai: 'E', au: 'O', kh: 'K', gh: 'G', ch: 'C', jh: 'J', 'ṭh': 'W', 'ḍh': 'Q',
  th: 'T', dh: 'D', ph: 'P', bh: 'B',
  'ā': 'A', 'ī': 'I', 'ū': 'U', 'ṛ': 'f', 'ṝ': 'F', 'ḷ': 'x', 'ḹ': 'X',
  'ṃ': 'M', 'ṁ': 'M', 'ḥ': 'H', 'ṅ': 'N', 'ñ': 'Y', 'ṭ': 'w', 'ḍ': 'q', 'ṇ': 'R',
  'ś': 'S', 'ṣ': 'z', 'ḻ': 'L',
  a: 'a', i: 'i', u: 'u', e: 'e', o: 'o', k: 'k', g: 'g', c: 'c', j: 'j',
  t: 't', d: 'd', n: 'n', p: 'p', b: 'b', m: 'm', y: 'y', r: 'r', l: 'l',
  v: 'v', s: 's', h: 'h',
};

function to_slp1(iast) {
  const s = iast || '';
  let out = '', i = 0;
  while (i < s.length) {
    const two = s.slice(i, i + 2);
    if (SLP1[two] !== undefined) { out += SLP1[two]; i += 2; continue; }
    const one = s[i];
    out += (SLP1[one] !== undefined ? SLP1[one] : one); i += 1;
  }
  return out;
}

const ROMAN = { 1: 'I', 2: 'II', 3: 'III', 4: 'IV', 5: 'V', 6: 'VI', 7: 'VII', 8: 'VIII', 9: 'IX', 10: 'X' };

function to_roman(nums) {
  return (nums || []).filter((n) => ROMAN[n] !== undefined).map((n) => ROMAN[n]);
}

// ---- SLP1 -> IAST ----
const FROM_SLP1 = {
  A: 'ā', I: 'ī', U: 'ū', f: 'ṛ', F: 'ṝ', x: 'ḷ', X: 'ḹ',
  E: 'ai', O: 'au', M: 'ṃ', H: 'ḥ',
  K: 'kh', G: 'gh', N: 'ṅ', C: 'ch', J: 'jh', Y: 'ñ',
  w: 'ṭ', W: 'ṭh', q: 'ḍ', Q: 'ḍh', R: 'ṇ',
  T: 'th', D: 'dh', P: 'ph', B: 'bh',
  S: 'ś', z: 'ṣ', L: 'ḻ',
};

function from_slp1(slp1) {
  let out = '';
  for (const ch of (slp1 || '')) out += (FROM_SLP1[ch] !== undefined ? FROM_SLP1[ch] : ch);
  return out;
}

// ---- Devanāgarī -> IAST (inherent-'a' + virāma aware) ----
const DV_VOWEL = { 'अ': 'a', 'आ': 'ā', 'इ': 'i', 'ई': 'ī', 'उ': 'u', 'ऊ': 'ū', 'ऋ': 'ṛ', 'ॠ': 'ṝ', 'ऌ': 'ḷ', 'ॡ': 'ḹ', 'ए': 'e', 'ऐ': 'ai', 'ओ': 'o', 'औ': 'au' };
const DV_MATRA = { 'ा': 'ā', 'ि': 'i', 'ी': 'ī', 'ु': 'u', 'ू': 'ū', 'ृ': 'ṛ', 'ॄ': 'ṝ', 'ॢ': 'ḷ', 'े': 'e', 'ै': 'ai', 'ो': 'o', 'ौ': 'au' };
const DV_CONS = { 'क': 'k', 'ख': 'kh', 'ग': 'g', 'घ': 'gh', 'ङ': 'ṅ', 'च': 'c', 'छ': 'ch', 'ज': 'j', 'झ': 'jh', 'ञ': 'ñ', 'ट': 'ṭ', 'ठ': 'ṭh', 'ड': 'ḍ', 'ढ': 'ḍh', 'ण': 'ṇ', 'त': 't', 'थ': 'th', 'द': 'd', 'ध': 'dh', 'न': 'n', 'प': 'p', 'फ': 'ph', 'ब': 'b', 'भ': 'bh', 'म': 'm', 'य': 'y', 'र': 'r', 'ल': 'l', 'व': 'v', 'श': 'ś', 'ष': 'ṣ', 'स': 's', 'ह': 'h', 'ळ': 'ḷ' };
const DV_MARK = { 'ं': 'ṃ', 'ः': 'ḥ', 'ँ': 'ṃ' };
const VIRAMA = '्';

function deva_to_iast(s) {
  s = s || '';
  let out = '';
  for (let i = 0; i < s.length; i++) {
    const ch = s[i];
    if (DV_CONS[ch] != null) {
      out += DV_CONS[ch];
      const nx = s[i + 1];
      if (nx === VIRAMA) { i++; }
      else if (DV_MATRA[nx] != null) { out += DV_MATRA[nx]; i++; }
      else { out += 'a'; }
    } else if (DV_VOWEL[ch] != null) { out += DV_VOWEL[ch]; }
    else if (DV_MARK[ch] != null) { out += DV_MARK[ch]; }
    else if (ch === 'ऽ') { /* avagraha — drop */ }
    else { out += ch; }
  }
  return out;
}

// ---- Devanāgarī -> SLP1 (direct; the ळ→L vs x decision is made HERE) ----
// deva_to_iast collapses ळ (U+0933, retroflex ḻa) onto vocalic ḷ (both render as IAST ḷ/U+1E37),
// so to_slp1(deva_to_iast('ळ')) would yield 'x' (vocalic ḷ) instead of 'L'. SLP1 keeps them apart
// and that can't be recovered after the IAST step, so we transcode Devanāgarī → SLP1 directly:
// derive the maps from the IAST maps (tracking to_slp1) and override ळ → 'L'. Round-trip partner
// of from_slp1 ('L' → ḻ), where to_slp1∘deva_to_iast is not. Mirror of the Python deva_to_slp1.
const mapVals = (m) => Object.fromEntries(Object.entries(m).map(([k, v]) => [k, to_slp1(v)]));
const DV_VOWEL_SLP1 = mapVals(DV_VOWEL);
const DV_MATRA_SLP1 = mapVals(DV_MATRA);
const DV_CONS_SLP1 = mapVals(DV_CONS);
DV_CONS_SLP1['ळ'] = 'L';        // retroflex ḻa — NOT 'x' (vocalic ḷ, from ऌ); see note above
const DV_MARK_SLP1 = mapVals(DV_MARK);

function deva_to_slp1(s) {
  s = s || '';
  let out = '';
  for (let i = 0; i < s.length; i++) {
    const ch = s[i];
    if (DV_CONS_SLP1[ch] != null) {
      out += DV_CONS_SLP1[ch];
      const nx = s[i + 1];
      if (nx === VIRAMA) { i++; }
      else if (DV_MATRA_SLP1[nx] != null) { out += DV_MATRA_SLP1[nx]; i++; }
      else { out += 'a'; }
    } else if (DV_VOWEL_SLP1[ch] != null) { out += DV_VOWEL_SLP1[ch]; }
    else if (DV_MARK_SLP1[ch] != null) { out += DV_MARK_SLP1[ch]; }
    else if (ch === 'ऽ') { /* avagraha — drop */ }
    else { out += ch; }
  }
  return out;
}

// ---- SLP1 -> Devanāgarī (real transcode: virāma conjuncts + mātrās) ----
// Round-trip partner of deva_to_slp1: for canonical SLP1, deva_to_slp1(slp1_to_devanagari(s)) == s
// (proved on the full alphabet + 1000 real MW headwords). Unlike iast_to_devanagari (a display-only
// replace), this supplies the virāma between clustered consonants and picks independent-vowel vs
// mātrā by position. The vowel/mātrā/consonant maps are INVERTED from the same Devanāgarī→SLP1 maps
// deva_to_slp1 uses (kept in lock-step); only the 3 marks are explicit (M→anusvāra, H→visarga,
// ~→candrabindu) since anusvāra and candrabindu both map back to 'M' and can't be inverted. Not
// round-trip stable (matching deva_to_slp1): candrabindu (~→ँ→'M') and avagraha ('→ऽ, dropped).
const invert = (m) => Object.fromEntries(Object.entries(m).map(([k, v]) => [v, k]));
const SLP1_TO_DV_VOWEL = invert(DV_VOWEL_SLP1);
const SLP1_TO_DV_MATRA = invert(DV_MATRA_SLP1);
SLP1_TO_DV_MATRA['a'] = '';        // inherent 'a' takes no sign
const SLP1_TO_DV_CONS = invert(DV_CONS_SLP1);
const SLP1_TO_DV_MARK = { M: 'ं', H: 'ः', '~': 'ँ' }; // anusvāra / visarga / candrabindu

function slp1_to_devanagari(slp1) {
  const s = slp1 || '';
  let out = '';
  let pendingCons = false;         // a consonant sign was emitted, still awaits its vowel/virāma
  for (const ch of s) {
    if (SLP1_TO_DV_CONS[ch] != null) {
      if (pendingCons) out += VIRAMA;               // previous consonant had no vowel -> conjunct
      out += SLP1_TO_DV_CONS[ch];
      pendingCons = true;
    } else if (SLP1_TO_DV_VOWEL[ch] != null) {
      if (pendingCons) { out += SLP1_TO_DV_MATRA[ch]; pendingCons = false; } // mātrā ('' for 'a')
      else out += SLP1_TO_DV_VOWEL[ch];             // independent vowel sign
    } else {                                        // mark, avagraha, accent, digit, space, other
      if (pendingCons) { out += VIRAMA; pendingCons = false; }
      if (ch === "'") out += 'ऽ';                   // avagraha
      else out += (SLP1_TO_DV_MARK[ch] != null ? SLP1_TO_DV_MARK[ch] : ch);
    }
  }
  if (pendingCons) out += VIRAMA;                   // trailing bare consonant
  return out;
}

// ---- IAST -> Devanāgarī (approximate display transcode) ----
const IAST_TO_DEVA = {
  a: 'अ', 'ā': 'आ', i: 'इ', 'ī': 'ई', u: 'उ', 'ū': 'ऊ', 'ṛ': 'ऋ', 'ṝ': 'ॠ', 'ḷ': 'ऌ', 'ḹ': 'ॡ',
  e: 'ए', ai: 'ऐ', o: 'ओ', au: 'औ', 'ṃ': 'ं', 'ḥ': 'ः',
  k: 'क', kh: 'ख', g: 'ग', gh: 'घ', 'ṅ': 'ङ',
  c: 'च', ch: 'छ', j: 'ज', jh: 'झ', 'ñ': 'ञ',
  'ṭ': 'ट', 'ṭh': 'ठ', 'ḍ': 'ड', 'ḍh': 'ढ', 'ṇ': 'ण',
  t: 'त', th: 'थ', d: 'द', dh: 'ध', n: 'न',
  p: 'प', ph: 'फ', b: 'ब', bh: 'भ', m: 'म',
  y: 'य', r: 'र', l: 'ल', v: 'व',
  'ś': 'श', 'ṣ': 'ष', s: 'स', h: 'ह',
};
const IAST_TO_DEVA_KEYS = Object.keys(IAST_TO_DEVA).sort((a, b) => b.length - a.length);

function iast_to_devanagari(text) {
  let result = (text || '').toLowerCase();
  for (const key of IAST_TO_DEVA_KEYS) {
    result = result.split(key).join(IAST_TO_DEVA[key]);
  }
  return result;
}

// ---- normalization keys ----
const DEVA_RE = /[ऀ-ॿ]/;

// Whitespace pinned to match the Python port's _WS_CHARS exactly. JS String.trim()/\s strip the
// BOM/ZWNBSP U+FEFF (which sneaks in when a file is read without a BOM-aware decoder) while Python
// str.strip()/\s do not (and conversely Python strips U+0085 NEL) — list the class explicitly so
// norm()/form_key()/slp1_norm() yield identical keys in both languages.
const WS = '\\t\\n\\x0b\\f\\r \\x85\\xa0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000\\ufeff';
const WS_TRIM_RE = new RegExp('^[' + WS + ']+|[' + WS + ']+$', 'g');
const WS_RUN_RE = new RegExp('[' + WS + ']+', 'g');
const wstrim = (s) => s.replace(WS_TRIM_RE, '');

function norm(s) {
  s = s || '';
  if (DEVA_RE.test(s)) s = deva_to_iast(s);
  return wstrim(s.normalize('NFD').replace(/\p{Mn}/gu, '').normalize('NFC').toLowerCase());
}

function nfold(s) {
  return norm(s).replace(/[mn]/g, 'n');
}

// ---- length-preserving comparison key ----
const FK_ACCENT = new Set(['́', '̀', '॑', '॒']); // acute, grave, Vedic svarita/anudātta
const FK_VOWELS = new Set([...'aāiīuūṛṝḷḹeēoō']);
const COMBINING_RE = /\p{Mn}/u;

function form_key(s) {
  s = wstrim(s || '').toLowerCase();
  if (s === '-' || s === '–' || s === '—') return '';
  s = s.replace(/ḥ$/, '');
  s = s.replace(/[ṃṁṅñṇ]/g, 'n');
  const out = [];
  for (const ch of s.normalize('NFD')) {
    if (FK_ACCENT.has(ch)) {
      let j = out.length - 1;
      while (j >= 0 && COMBINING_RE.test(out[j])) j -= 1;
      const base = j >= 0 ? out.slice(j).join('').normalize('NFC') : '';
      if (FK_VOWELS.has(base)) continue;
    }
    out.push(ch);
  }
  return out.join('').normalize('NFC');
}

// ---- lossy ASCII-folding search key (v3-explorer normalizeSanskrit) ----
const NS_MAP = {
  'ā': 'a', 'ī': 'i', 'ū': 'u', 'ṛ': 'r', 'ṝ': 'r', 'ḷ': 'l', 'ḹ': 'l',
  'ṅ': 'n', 'ñ': 'n', 'ṭ': 't', 'ḍ': 'd', 'ṇ': 'n', 'ś': 's', 'ṣ': 's',
  'ḥ': 'h', 'ṃ': 'm',
};

function normalize_sanskrit(text) {
  if (!text) return '';
  return text.normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[āīūṛṝḷḹṅñṭḍṇśṣḥṃ]/g, (m) => NS_MAP[m] || m)
    .toLowerCase();
}

// ---- SLP1-side API ----
// The CDSL dictionaries store headwords in SLP1, where case is PHONEMIC (S=ś≠s) — so the
// IAST helpers above can't key them without a transcode, and every CDSL repo re-rolled its own
// SLP1 alphabet + headword normalizer. Behaviour-identical port of the Python additions.
const SLP1_VOWELS = 'aAiIuUfFxXeEoO';                          // f/F=ṛ/ṝ, x/X=ḷ/ḹ, E=ai, O=au
const SLP1_MARKS = 'MH~';                                     // anusvāra, visarga, candrabindu
const SLP1_CONSONANTS = 'kKgGNcCjJYwWqQRtTdDnpPbBmyrlvSzshL'; // L = Vedic retroflex ḻa
const SLP1_ALPHABET = SLP1_VOWELS + SLP1_MARKS + SLP1_CONSONANTS; // valid SLP1 letters (no avagraha)

const SLP1_ACCENTS_RE = /[/\\^~]/g; // udātta / anudātta / svarita / candrabindu

function strip_slp1_accents(slp1) {
  return (slp1 ?? '').replace(SLP1_ACCENTS_RE, '');
}

function slp1_norm(slp1) {
  let s = strip_slp1_accents(slp1 ?? '');
  s = s.replace(/\d+$/, '');
  return wstrim(s.replace(WS_RUN_RE, ' '));
}

function slp1_form_key(slp1) {
  return form_key(from_slp1(strip_slp1_accents(slp1 ?? '')));
}

// Fuzzy-match key: fold ALL SLP1 distinctions to plain ASCII — the lossy extreme of the SLP1 key
// family. For building/querying MW headword indexes (mw_en_tm.json); index and query sides agree
// because both use standard SLP1 (R=ṇ). ⚠️ guṇa = 'guRa' in MW — forgetting R→n maps it to 'gūna'.
function slp1_simplify(slp1) {
  let s = slp1 || '';
  s = s.replace(/K/g, 'kh').replace(/G/g, 'gh')
    .replace(/C/g, 'ch').replace(/J/g, 'jh')
    .replace(/T/g, 'th').replace(/D/g, 'dh')
    .replace(/P/g, 'ph').replace(/B/g, 'bh');
  s = s.replace(/S/g, 's').replace(/z/g, 's');
  s = s.replace(/Y/g, 'n').replace(/N/g, 'n').replace(/R/g, 'n');   // R=ṇ is the critical case
  s = s.replace(/A/g, 'a').replace(/I/g, 'i').replace(/U/g, 'u');
  s = s.replace(/E/g, 'ai').replace(/O/g, 'au');
  s = s.replace(/f/g, 'r').replace(/F/g, 'r').replace(/x/g, 'l').replace(/X/g, 'l');
  s = s.replace(/M/g, 'm').replace(/H/g, '');
  s = s.replace(/W/g, 'th').replace(/Q/g, 'dh');
  s = s.replace(/w/g, 't').replace(/q/g, 'd');
  s = s.replace(/L/g, 'l');                                         // Vedic retroflex ḻa
  return s.toLowerCase();
}

// ---- CDSL raw source line -> readable IAST (display layer over from_slp1) ----
// A raw csl-orig line is SLP1 inside CDSL markup, unreadable to a human. These
// render it to IAST honoring each dictionary's encoding: MW <s>…</s>;
// PW/PWG/AP/WIL {#…#} (with the meaning language in {%…%}, left as-is);
// VCP/SKD whole-line SLP1 prose. The markup shell (tags, [Page…] markers, the ¦
// headword separator) is stripped. `code` is the csl-orig dict code
// (mw, ap, pwg, pw, wil, vcp, skd). Non-SLP1 spans — glosses, <ls> citations,
// grammar abbreviations like "f." — are preserved.
const _PROSE_SLP1_DICTS = new Set(['vcp', 'skd']);

function _stripCdslMarkup(text) {
  return text
    .replace(/<info[^>]*\/?>/gi, '')   // metadata self-closing tags
    .replace(/\[Page[^\]]*\]/g, '')    // VCP/SKD page markers
    .replace(/<[^>]+>/g, '');          // any remaining tag shell
}

function _cleanCdsl(text) {
  return text
    .replace(/¦/g, ' ')                // ¦ headword/body separator
    .replace(/\s+([,.;:!?])/g, '$1')   // pull punctuation back
    .replace(/\s+/g, ' ')
    .trim();
}

function source_line_to_iast(text, code) {
  if (text == null) return '';
  const c = String(code || '').toLowerCase();
  if (_PROSE_SLP1_DICTS.has(c)) {
    const s = String(text).replace(/[A-Za-z~']+/g, (m) => from_slp1(m));
    return _cleanCdsl(_stripCdslMarkup(s));
  }
  let s = String(text);
  s = s.replace(/\{[#@]([^#@]*)[#@]\}/g, (_, x) => from_slp1(x));   // {#…#}, {@…@}
  s = s.replace(/<s\d?>([^<]*)<\/s\d?>/gi, (_, x) => from_slp1(x)); // MW <s>…</s>
  s = s.replace(/\{%([^%]*)%\}/g, (_, x) => x);                    // meaning: unwrap, keep
  return _cleanCdsl(_stripCdslMarkup(s));
}

function source_text_to_iast(text, code) {
  if (text == null) return '';
  return String(text).split('\n').map((l) => source_line_to_iast(l, code)).join('\n');
}

  root.SanskritUtil = Object.freeze({
    to_slp1, to_roman, from_slp1, deva_to_iast, deva_to_slp1, slp1_to_devanagari, iast_to_devanagari, norm, nfold, form_key, normalize_sanskrit, SLP1_VOWELS, SLP1_MARKS, SLP1_CONSONANTS, SLP1_ALPHABET, strip_slp1_accents, slp1_norm, slp1_form_key, slp1_simplify, source_line_to_iast, source_text_to_iast,
  });
})(typeof globalThis !== 'undefined' ? globalThis : this);
